version: '3.5'

services:
  todo-postgres:
    container_name: todo-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - ./.data/postgres:/data/postgres
    ports:
      - "5432:5432"
    
volumes:
  postgres: